Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

Lint/Eval:
  Enabled: false

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 25
